/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/ashish/catkin_ws/src/urc15/msg/Comm_DataArray.msg
 *
 */


#ifndef URC15_MESSAGE_COMM_DATAARRAY_H
#define URC15_MESSAGE_COMM_DATAARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace urc15
{
template <class ContainerAllocator>
struct Comm_DataArray_
{
  typedef Comm_DataArray_<ContainerAllocator> Type;

  Comm_DataArray_()
    : datas()  {
    }
  Comm_DataArray_(const ContainerAllocator& _alloc)
    : datas(_alloc)  {
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _datas_type;
  _datas_type datas;




  typedef boost::shared_ptr< ::urc15::Comm_DataArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::urc15::Comm_DataArray_<ContainerAllocator> const> ConstPtr;

}; // struct Comm_DataArray_

typedef ::urc15::Comm_DataArray_<std::allocator<void> > Comm_DataArray;

typedef boost::shared_ptr< ::urc15::Comm_DataArray > Comm_DataArrayPtr;
typedef boost::shared_ptr< ::urc15::Comm_DataArray const> Comm_DataArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::urc15::Comm_DataArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::urc15::Comm_DataArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace urc15

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'urc15': ['/home/ashish/catkin_ws/src/urc15/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::urc15::Comm_DataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::urc15::Comm_DataArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::urc15::Comm_DataArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::urc15::Comm_DataArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::urc15::Comm_DataArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::urc15::Comm_DataArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::urc15::Comm_DataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69dfad1a6ee9f07f2a78619e47508622";
  }

  static const char* value(const ::urc15::Comm_DataArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69dfad1a6ee9f07fULL;
  static const uint64_t static_value2 = 0x2a78619e47508622ULL;
};

template<class ContainerAllocator>
struct DataType< ::urc15::Comm_DataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "urc15/Comm_DataArray";
  }

  static const char* value(const ::urc15::Comm_DataArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::urc15::Comm_DataArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] datas\n\
";
  }

  static const char* value(const ::urc15::Comm_DataArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::urc15::Comm_DataArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.datas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Comm_DataArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::urc15::Comm_DataArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::urc15::Comm_DataArray_<ContainerAllocator>& v)
  {
    s << indent << "datas[]" << std::endl;
    for (size_t i = 0; i < v.datas.size(); ++i)
    {
      s << indent << "  datas[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.datas[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // URC15_MESSAGE_COMM_DATAARRAY_H
